on: push
name: deploy
jobs:
  build-and-push:
    name: build and push image
    runs-on: ubuntu-latest     ## VM que corre github para correr nuestro codigo
    steps:
    - uses: actions/checkout@master  ## se descarga nuestro repo (checkout) y lo coloca en nuestra VM 
    - name: build and push to docker     ## construye nuestra img 
      uses: docker/build-push-action@v2  ## sube nustra img al hub de docker
      with:    ## opciones especificas para nuestra action
        username: ${{ secrets.DOCKER_USERNAME }}  ## credenciales de nuestro docker hub
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ github.repository }}
