on: push
name: deploy
jobs:
  build-and-push:
    name: build and push image
    runs-on: ubuntu-latest     ## VM que corre github para correr nuestro codigo
    steps:
    - uses: actions/checkout@master  ## se descarga nuestro repo (checkout) y lo coloca en nuestra VM 
    - name: build and push to docker     ## construye nuestra img 
      uses: docker/build-push-action@v1  ## sube nustra img al hub de docker
      with:    ## opciones especificas para nuestra action
        username: ${{ secrets.DOCKER_USERNAME }}  ## credenciales de nuestro docker hub
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ github.repository }}
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}
        
#  deploy-to-cluster:
#     name: deploy to cluster
#     runs-on: ubuntu-latest
#     needs: build-and-push
#     steps:
#     - name: deploy to cluster
#       uses: steebchen/kubectl@master
#       env:
